using System.Collections.Generic;

namespace GTAN.Data
{
    public static class VehicleDicts
    {
        public static IReadOnlyDictionary<string, uint> Bicycle { get; } = new Dictionary<string, uint>
        {
            {"Bmx", (uint)OriginalVehicles.Bmx },
            {"Cruiser", (uint)OriginalVehicles.Cruiser },
            {"Fixter", (uint)OriginalVehicles.Fixter },
            {"Scorcher", (uint)OriginalVehicles.Scorcher },
            {"TriBike", (uint)OriginalVehicles.TriBike },
            {"TriBike2", (uint)OriginalVehicles.TriBike2 },
            {"TriBike3", (uint)OriginalVehicles.TriBike3 },
        };
        public static IReadOnlyDictionary<string, uint> Boat { get; } = new Dictionary<string, uint>
        {
            {"Dinghy", (uint)OriginalVehicles.Dinghy },
            {"Dinghy2", (uint)OriginalVehicles.Dinghy2 },
            {"Dinghy3", (uint)HeistsVehicles.Dinghy3 },
            {"Dinghy4", (uint)ExecutiveVehicles.Dinghy4 },
            {"Jetmax", (uint)OriginalVehicles.Jetmax },
            {"Marquis", (uint)OriginalVehicles.Marquis },
            {"Seashark", (uint)OriginalVehicles.Seashark },
            {"Seashark2", (uint)OriginalVehicles.Seashark2 },
            {"Seashark3", (uint)ExecutiveVehicles.Seashark3 },
            {"Speeder", (uint)BeachBumVehicles.Speeder },
            {"Speeder2", (uint)ExecutiveVehicles.Speeder2 },
            {"Squalo", (uint)OriginalVehicles.Squalo },
            {"Submersible", (uint)OriginalVehicles.Submersible },
            {"Submersible2", (uint)SPUpgradeVehicles.Submersible2 },
            {"Suntrap", (uint)OriginalVehicles.Suntrap },
            {"Toro", (uint)IllGottenGainsPt2Vehicles.Toro },
            {"Toro2", (uint)ExecutiveVehicles.Toro2},
            {"Tropic", (uint)OriginalVehicles.Tropic},
            {"Tropic2", (uint)OriginalVehicles.Tropic2},
            {"Tug", (uint)FinanceFelonyVehicles.Tug}
        };
        public static IReadOnlyDictionary<string, uint> Commercial { get; } = new Dictionary<string, uint>
        {
            {"Benson", (uint)OriginalVehicles.Benson },
            {"Biff", (uint)OriginalVehicles.Biff },
            {"Hauler", (uint)OriginalVehicles.Hauler },
            {"Hauler2", (uint)GunrunningVehicles.HAULER2 },
            {"Mule", (uint)OriginalVehicles.Mule },
            {"Mule2", (uint)OriginalVehicles.Mule2 },
            {"Packer", (uint)OriginalVehicles.Packer },
            {"Phantom", (uint)OriginalVehicles.Phantom },
            {"Phantom2", (uint)ImportExportVehicles.PHANTOM2 },
            {"Phantom3", (uint)GunrunningVehicles.PHANTOM3 },
            {"Pounder", (uint)OriginalVehicles.Pounder },
            {"Stockade", (uint)OriginalVehicles.Stockade },
            {"Stockade3", (uint)OriginalVehicles.Stockade3 },
        };
        public static IReadOnlyDictionary<string, uint> Compact { get; } = new Dictionary<string, uint>
        {
            {"Blista", (uint)OriginalVehicles.Blista },
            {"Blista2", (uint)SPUpgradeVehicles.Blista2 },
            {"Blista3", (uint)SPUpgradeVehicles.Blista3 },
            {"Brioso", (uint)CunningStuntsVehicles.Brioso },
            {"Dilettante", (uint)OriginalVehicles.Dilettante},
            {"Dilettante2", (uint)OriginalVehicles.Dilettante2},
            {"Issi2", (uint)OriginalVehicles.Issi2},
            {"Panto", (uint)HipsterVehicles.Panto},
            {"Prairie", (uint)OriginalVehicles.Prairie},
            {"Rhapsody", (uint)HipsterVehicles.Rhapsody},
        };
        public static IReadOnlyDictionary<string, uint> Coupe { get; } = new Dictionary<string, uint>
        {
            {"CogCabrio", (uint)OriginalVehicles.CogCabrio },
            {"Exemplar", (uint)OriginalVehicles.Exemplar },
            {"F620", (uint)OriginalVehicles.F620 },
            {"Felon", (uint)OriginalVehicles.Felon },
            {"Felon2", (uint)OriginalVehicles.Felon2 },
            {"Jackal", (uint)OriginalVehicles.Jackal },
            {"Oracle", (uint)OriginalVehicles.Oracle },
            {"Oracle2", (uint)OriginalVehicles.Oracle2 },
            {"Sentinel", (uint)OriginalVehicles.Sentinel },
            {"Sentinel2", (uint)OriginalVehicles.Sentinel2 },
            {"Windsor", (uint)IllGottenGainsPt1Vehicles.Windsor },
            {"Windsor2", (uint)FinanceFelonyVehicles.Windsor2 },
            {"Zion", (uint)OriginalVehicles.Zion },
            {"Zion2", (uint)OriginalVehicles.Zion2 },
        };        
        public static IReadOnlyDictionary<string, uint> EmergencyAirSea { get; } = new Dictionary<string, uint>
        {
            {"PolmavHeli", (uint) OriginalVehicles.Polmav },
            {"PredatorBoat", (uint) OriginalVehicles.Predator },
        };
        public static IReadOnlyDictionary<string, uint> EmergencyCar { get; } = new Dictionary<string, uint>
        {
            {"FBI", (uint) OriginalVehicles.FBI },
            {"FBI2", (uint) OriginalVehicles.FBI2 },
            {"Police", (uint) OriginalVehicles.Police },
            {"Police2", (uint) OriginalVehicles.Police2 },
            {"Police3", (uint) OriginalVehicles.Police3 },
            {"Police4", (uint) OriginalVehicles.Police4 },
            {"Policebike", (uint) OriginalVehicles.Policeb },
            {"PoliceOld1", (uint) OriginalVehicles.PoliceOld1 },
            {"PoliceOld2", (uint) OriginalVehicles.PoliceOld2 },
            {"PoliceT", (uint) OriginalVehicles.PoliceT },
            {"Pranger", (uint) OriginalVehicles.Pranger },
            {"Sheriff", (uint) OriginalVehicles.Sheriff },
            {"Sheriff2", (uint) OriginalVehicles.Sheriff2 },
        };
        public static IReadOnlyDictionary<string, uint> EmergencyTruck { get; } = new Dictionary<string, uint>
        {
            {"Ambulance", (uint)OriginalVehicles.Ambulance },
            {"FireTruck", (uint)OriginalVehicles.FireTruck },
            {"PBus", (uint)OriginalVehicles.PBus },
            {"Riot", (uint)OriginalVehicles.Riot },
        };
        public static IReadOnlyDictionary<string, uint> Helicopter { get; } = new Dictionary<string, uint>
        {
            {"Annihilator", (uint)OriginalVehicles.Annihilator },
            {"Buzzard", (uint)OriginalVehicles.Buzzard },
            {"Buzzard2", (uint)OriginalVehicles.Buzzard2 },
            {"Cargobob", (uint)OriginalVehicles.Cargobob },
            {"Cargobob2", (uint)OriginalVehicles.Cargobob2 },
            {"Cargobob3", (uint)OriginalVehicles.Cargobob3 },
            {"Cargobob4", (uint)ExecutiveVehicles.Cargobob4 },
            {"Frogger", (uint)OriginalVehicles.Frogger },
            {"Frogger2", (uint)OriginalVehicles.Frogger2 },
            {"Maverick", (uint)OriginalVehicles.Maverick },
            {"Savage", (uint)HeistsVehicles.Savage },
            {"Skylift", (uint)OriginalVehicles.Skylift },
            {"Supervolito", (uint)ExecutiveVehicles.Supervolito },
            {"Supervolito2", (uint)ExecutiveVehicles.Supervolito2 },
            {"Swift", (uint)FlightSchoolVehicles.Swift },
            {"Swift2", (uint)IllGottenGainsPt1Vehicles.Swift2 },
            {"Valkyrie", (uint)HeistsVehicles.Valkyrie },
            {"Valkyrie2", (uint)ExecutiveVehicles.Valkyrie2 },
            {"Volatus", (uint)FinanceFelonyVehicles.Volatus },
        };
        public static IReadOnlyDictionary<string, uint> Industrial { get; } = new Dictionary<string, uint>
        {
            {"Bulldozer", (uint)OriginalVehicles.Bulldozer },
            {"Cutter", (uint)OriginalVehicles.Cutter },
            {"Dump", (uint)OriginalVehicles.Dump },
            {"Flatbed", (uint)OriginalVehicles.Flatbed },
            {"Guardian", (uint)HeistsVehicles.Guardian },
            {"Handler", (uint)OriginalVehicles.Handler },
            {"Mixer", (uint)OriginalVehicles.Mixer },
            {"Mixer2", (uint)OriginalVehicles.Mixer2 },
            {"Rubble", (uint)OriginalVehicles.Rubble },
            {"TipTruck", (uint)OriginalVehicles.TipTruck },
            {"TipTruck2", (uint)OriginalVehicles.TipTruck2 },
        };
        public static IReadOnlyDictionary<string, uint> Military { get; } = new Dictionary<string, uint>
        {
            {"APC", (uint)GunrunningVehicles.APC },
            {"Barracks", (uint)OriginalVehicles.Barracks },
            {"Barracks2", (uint)OriginalVehicles.Barracks2 },
            {"Barracks3", (uint)HeistsVehicles.Barracks3 },
            {"Crusader", (uint)OriginalVehicles.Crusader },
            {"Halftrack", (uint)GunrunningVehicles.HALFTRACK },
            {"Rhino", (uint)OriginalVehicles.Rhino },
            {"Trailersmall2", (uint)GunrunningVehicles.TRSMALL2 },
        };
        public static IReadOnlyDictionary<string, uint> Motorcycle { get; } = new Dictionary<string, uint>
        {
            {"Akuma", (uint)OriginalVehicles.Akuma },
            {"Avarus", (uint)Bikers.Avarus },
            {"Bagger", (uint)OriginalVehicles.Bagger },
            {"Bati", (uint)OriginalVehicles.Bati },
            {"Bati2", (uint)OriginalVehicles.Bati2 },
            {"BF400", (uint)CunningStuntsVehicles.BF400 },
            {"Blazer4", (uint)Bikers.Blazer4 },
            {"CarbonRS", (uint)OriginalVehicles.CarbonRS },
            {"Chimera", (uint)Bikers.Chimera },
            {"Cliffhanger", (uint)CunningStuntsVehicles.Cliffhanger },
            {"Daemon", (uint)OriginalVehicles.Daemon },
            {"Daemon2", (uint)Bikers.Daemon2 },
            {"Defiler", (uint)Bikers.Defiler },
            {"Double", (uint)OriginalVehicles.Double },
            {"Enduro", (uint)HeistsVehicles.Enduro },
            {"Esskey", (uint)Bikers.Esskey },
            {"Faggio", (uint)Bikers.Faggio },
            {"Faggio2", (uint)OriginalVehicles.Faggio2 },
            {"Faggio3", (uint)Bikers.Faggio3 },
            {"Fcr", (uint)ImportExportVehicles.FCR },
            {"Fcr2", (uint)ImportExportVehicles.FCR2 },
            {"Gargoyle", (uint)CunningStuntsVehicles.Gargoyle },
            {"Hakuchou", (uint)LTSVehicles.Hakuchou },
            {"Hakuchou2", (uint)Bikers.Hakuchou2 },
            {"Hexer", (uint)OriginalVehicles.Hexer },
            {"Innovation", (uint)LTSVehicles.Innovation },
            {"Lectro", (uint)HeistsVehicles.Lectro },
            {"Manchez", (uint)Bikers.Manchez },
            {"Nemesis", (uint)OriginalVehicles.Nemesis },
            {"Nightblade", (uint)Bikers.Nightblade },
            {"Opressor", (uint)GunrunningVehicles.OPPRESSOR },
            {"PCJ", (uint)OriginalVehicles.PCJ },
            {"Ratbike", (uint)Bikers.Ratbike },
            {"Ruffian", (uint)OriginalVehicles.Ruffian },
            {"Sanchez2", (uint)OriginalVehicles.Sanchez2 },
            {"Sanchez", (uint)OriginalVehicles.Sanchez },
            {"Sanctus", (uint)Bikers.Sanctus },
            {"Shotaro", (uint)Bikers.Shotaro },
            {"Sovereign", (uint)MURKAVehicles.Sovereign },
            {"Thrust", (uint)HighLifeVehicles.Thrust },
            {"Vader", (uint)OriginalVehicles.Vader },
            {"Vindicator", (uint)IllGottenGainsPt2Vehicles.Vindicator },
            {"Vortex", (uint)Bikers.Vortex },
            {"Wolfsbane", (uint)Bikers.Wolfsbane },
            {"Zombiea", (uint)Bikers.Zombiea },
            {"Zombieb", (uint)Bikers.Zombieb },

        };
        public static IReadOnlyDictionary<string, uint> Muscle { get; } = new Dictionary<string, uint>
        {
            {"Blade", (uint)HipsterVehicles.Blade },
            {"Buccaneer", (uint)OriginalVehicles.Buccaneer },
            {"Buccaneer2", (uint)LowriderVehicles.Buccaneer2 },
            {"Chino", (uint)IllGottenGainsPt2Vehicles.Chino },
            {"Chino2", (uint)LowriderVehicles.Chino2 },
            {"Dominator", (uint)OriginalVehicles.Dominator },
            {"Dominator2", (uint)SPUpgradeVehicles.Dominator2 },
            {"Dukes", (uint)SPUpgradeVehicles.Dukes },
            {"Dukes2", (uint)SPUpgradeVehicles.Dukes2 },
            {"Faction", (uint)LowriderVehicles.Faction },
            {"Faction2", (uint)LowriderVehicles.Faction2 },
            {"Faction3", (uint)LowriderCCVehicles.Faction3 },
            {"Gauntlet", (uint)OriginalVehicles.Gauntlet },
            {"Gauntlet2", (uint)SPUpgradeVehicles.Gauntlet2 },
            {"Hotknife", (uint)OriginalVehicles.Hotknife },
            {"Lurcher", (uint)HalloweenVehicles.Lurcher },
            {"Moonbeam", (uint)LowriderVehicles.Moonbeam },
            {"Moonbeam2", (uint)LowriderVehicles.Moonbeam2 },
            {"Nightshade", (uint)ExecutiveVehicles.Nightshade },
            {"Phoenix", (uint)OriginalVehicles.Phoenix },
            {"Picador", (uint)OriginalVehicles.Picador },
            {"RatLoader", (uint)OriginalVehicles.RatLoader },
            {"RatLoader2", (uint)FestiveVehicles.RatLoader2 },
            {"Ruiner", (uint)OriginalVehicles.Ruiner },
            {"Ruiner2", (uint)ImportExportVehicles.RUINER2 },
            {"SabreGT", (uint)OriginalVehicles.SabreGT },
            {"SabreGT2", (uint)LowriderCCVehicles.SabreGT2 },
            {"Sadler2", (uint)OriginalVehicles.Sadler2 },
            {"SlamVan", (uint)FestiveVehicles.SlamVan },
            {"SlamVan2", (uint)HeistsVehicles.SlamVan2 },
            {"SlamVan3", (uint)LowriderCCVehicles.SlamVan3 },
            {"Stalion", (uint)SPUpgradeVehicles.Stalion },
            {"Stalion2", (uint)SPUpgradeVehicles.Stalion2 },
            {"Tampa", (uint)ValentineVehicles.Tampa },
            {"Tampa3", (uint)GunrunningVehicles.TAMPA3 },
            {"Vigero", (uint)OriginalVehicles.Vigero },
            {"Virgo", (uint)IllGottenGainsPt1Vehicles.Virgo },
            {"Virgo2", (uint)LowriderCCVehicles.Virgo2 },
            {"Virgo3", (uint)LowriderCCVehicles.Virgo3 },
            {"Voodoo", (uint)LowriderVehicles.Voodoo },
            {"Voodoo2", (uint)OriginalVehicles.Voodoo2 },
        };
        public static IReadOnlyDictionary<string, uint> OffRoad { get; } = new Dictionary<string, uint>
        {
            {"BfInjection", (uint)OriginalVehicles.BfInjection },
            {"Bifta", (uint)BeachBumVehicles.Bifta },
            {"Blazer", (uint)OriginalVehicles.Blazer },
            {"Blazer2", (uint)OriginalVehicles.Blazer2 },
            {"Blazer3", (uint)OriginalVehicles.Blazer3 },
            {"Blazer5", (uint)ImportExportVehicles.BLAZER5 },
            {"Bodhi2", (uint)OriginalVehicles.Bodhi2 },
            {"Brawler", (uint)IllGottenGainsPt2Vehicles.Brawler },
            {"DLoader", (uint)OriginalVehicles.DLoader },
            {"Dune", (uint)OriginalVehicles.Dune },
            {"Dune2", (uint)OriginalVehicles.Dune2 },
            {"Dune3", (uint)GunrunningVehicles.DUNE3 },
            {"Dune4", (uint)ImportExportVehicles.DUNE4 },
            {"Dune5", (uint)ImportExportVehicles.DUNE5 },
            {"Insurgent", (uint)HeistsVehicles.Insurgent },
            {"Insurgent2", (uint)HeistsVehicles.Insurgent2 },
            {"Insurgent3", (uint)GunrunningVehicles.INSURGENT3 },
            {"Kalahari", (uint)BeachBumVehicles.Kalahari },
            {"Lguard", (uint)OriginalVehicles.Lguard },
            {"Marshall", (uint)SPUpgradeVehicles.Marshall },
            {"Mesa", (uint)OriginalVehicles.Mesa },
            {"Mesa2", (uint)OriginalVehicles.Mesa2 },
            {"Mesa3", (uint)OriginalVehicles.Mesa3 },
            {"Monster", (uint)MURKAVehicles.Monster },
            {"Nightshark", (uint)GunrunningVehicles.NIGHTSHARK },
            {"RancherXL", (uint)OriginalVehicles.RancherXL },
            {"RancherXL2", (uint)OriginalVehicles.RancherXL2 },
            {"Rebel", (uint)OriginalVehicles.Rebel },
            {"Rebel2", (uint)OriginalVehicles.Rebel2 },
            {"Sandking", (uint)OriginalVehicles.Sandking },
            {"Sandking2", (uint)OriginalVehicles.Sandking2 },
            {"Technical", (uint)HeistsVehicles.Technical },
            {"Technical2", (uint)ImportExportVehicles.TECHNICAL2},
            {"Technical3", (uint)GunrunningVehicles.TECHNICAL3 },
            {"TrophyTruck", (uint)CunningStuntsVehicles.TrophyTruck },
            {"TrophyTruck2", (uint)CunningStuntsVehicles.TrophyTruck2 },
        };
        public static IReadOnlyDictionary<string, uint> Plane { get; } = new Dictionary<string, uint>
        {
            {"Besra", (uint)FlightSchoolVehicles.Besra },
            {"Blimp", (uint)OriginalVehicles.Blimp },
            {"Blimp2", (uint)SPUpgradeVehicles.Blimp2 },
            {"CargoPlane", (uint)OriginalVehicles.CargoPlane},
            {"Cuban800", (uint)OriginalVehicles.Cuban800 },
            {"Dodo", (uint)SPUpgradeVehicles.Dodo },
            {"Duster", (uint)OriginalVehicles.Duster },
            {"Hydra", (uint)HeistsVehicles.Hydra },
            {"Jet", (uint)OriginalVehicles.Jet },
            {"Lazer", (uint)OriginalVehicles.Lazer },
            {"Luxor", (uint)OriginalVehicles.Luxor },
            {"Luxor2", (uint)IllGottenGainsPt1Vehicles.Luxor2 },
            {"Mammatus", (uint)OriginalVehicles.Mammatus },
            {"Miljet", (uint)FlightSchoolVehicles.Miljet },
            {"Nimbus", (uint)FinanceFelonyVehicles.Nimbus },
            {"Shamal", (uint)OriginalVehicles.Shamal },
            {"Stunt", (uint)OriginalVehicles.Stunt },
            {"Titan", (uint)OriginalVehicles.Titan },
            {"Velum", (uint)OriginalVehicles.Velum },
            {"Velum2", (uint)HeistsVehicles.Velum2 },
            {"Vestra", (uint)BusinessVehicles.Vestra },
        };
        public static IReadOnlyDictionary<string, uint> Suv { get; } = new Dictionary<string, uint>
        {
            {"BJXL", (uint)OriginalVehicles.BJXL },
            {"Baller", (uint)OriginalVehicles.Baller },
            {"Baller2", (uint)OriginalVehicles.Baller2 },
            {"Baller3", (uint)ExecutiveVehicles.Baller3 },
            {"Baller4", (uint)ExecutiveVehicles.Baller4 },
            {"Baller5", (uint)ExecutiveVehicles.Baller5 },
            {"Baller6", (uint)ExecutiveVehicles.Baller6 },
            {"Cavalcade", (uint)OriginalVehicles.Cavalcade },
            {"Cavalcade2", (uint)OriginalVehicles.Cavalcade2 },
            {"Contender", (uint)CunningStuntsVehicles.Contender },
            {"Dubsta", (uint)OriginalVehicles.Dubsta },
            {"Dubsta2", (uint)OriginalVehicles.Dubsta2 },
            {"Dubsta3", (uint)HipsterVehicles.Dubsta3 },
            {"FQ2", (uint)OriginalVehicles.FQ2 },
            {"Granger", (uint)OriginalVehicles.Granger },
            {"Gresley", (uint)OriginalVehicles.Gresley },
            {"Habanero", (uint)OriginalVehicles.Habanero },
            {"Huntley", (uint)HighLifeVehicles.Huntley },
            {"Landstalker", (uint)OriginalVehicles.Landstalker },
            {"Patriot", (uint)OriginalVehicles.Patriot },
            {"Radi", (uint)OriginalVehicles.Radi },
            {"Rocoto", (uint)OriginalVehicles.Rocoto },
            {"Seminole", (uint)OriginalVehicles.Seminole },
            {"Serrano", (uint)OriginalVehicles.Serrano },
            {"XLS", (uint)FinanceFelonyVehicles.XLS },
            {"XLS2", (uint)FinanceFelonyVehicles.XLS2 },
        };
        public static IReadOnlyDictionary<string, uint> Sedan { get; } = new Dictionary<string, uint>
        {
            {"Asea", (uint)OriginalVehicles.Asea },
            {"Asea2", (uint)OriginalVehicles.Asea2 },
            {"Asterope", (uint)OriginalVehicles.Asterope },
            {"Cog55", (uint)ExecutiveVehicles.Cog55 },
            {"Cog552", (uint)ExecutiveVehicles.Cog552 },
            {"Cognoscenti", (uint)ExecutiveVehicles.Cognoscenti },
            {"Cognoscenti2", (uint)ExecutiveVehicles.Cognoscenti2 },
            {"Emperor", (uint)OriginalVehicles.Emperor },
            {"Emperor2", (uint)OriginalVehicles.Emperor2 },
            {"Fugitive", (uint)OriginalVehicles.Fugitive },
            {"Glendale", (uint)HipsterVehicles.Glendale },
            {"Ingot", (uint)OriginalVehicles.Ingot },
            {"Intruder", (uint)OriginalVehicles.Intruder },
            {"Limo2", (uint)ExecutiveVehicles.Limo2 },
            {"Premier", (uint)OriginalVehicles.Premier },
            {"Primo", (uint)OriginalVehicles.Primo },
            {"Primo2", (uint)LowriderVehicles.Primo2 },
            {"Regina", (uint)OriginalVehicles.Regina },
            {"Romero", (uint)OriginalVehicles.Romero },
            {"Stanier", (uint)OriginalVehicles.Stanier },
            {"Stratum", (uint)OriginalVehicles.Stratum },
            {"Stretch", (uint)OriginalVehicles.Stretch },
            {"Surge", (uint)OriginalVehicles.Surge },
            {"Tailgater", (uint)OriginalVehicles.Tailgater },
            {"Warrener", (uint)HipsterVehicles.Warrener },
            {"Washington", (uint)OriginalVehicles.Washington },
        };
        public static IReadOnlyDictionary<string, uint> Service { get; } = new Dictionary<string, uint>
        {
            {"Airbus", (uint)OriginalVehicles.Airbus },
            {"Brickade", (uint)FinanceFelonyVehicles.Brickade },
            {"Bus", (uint)OriginalVehicles.Bus },
            {"Coach", (uint)OriginalVehicles.Coach },
            {"Rallytruck", (uint)CunningStuntsVehicles.Rallytruck },
            {"RentalBus", (uint)OriginalVehicles.RentalBus },
            {"Taxi", (uint)OriginalVehicles.Taxi },
            {"Tourbus", (uint)OriginalVehicles.Tourbus },
            {"Trash", (uint)OriginalVehicles.Trash },
            {"Trash2", (uint)HeistsVehicles.Trash2 },
        };
        public static IReadOnlyDictionary<string, uint> Sport { get; } = new Dictionary<string, uint>
        {
            {"Alpha", (uint)BusinessVehicles.Alpha },
            {"Banshee", (uint)OriginalVehicles.Banshee },
            {"Banshee2", (uint)DropzoneVehicles.Banshee2 },
            {"BestiaGTS", (uint)FinanceFelonyVehicles.BestiaGTS },
            {"Buffalo", (uint)OriginalVehicles.Buffalo },
            {"Buffalo2", (uint)OriginalVehicles.Buffalo2 },
            {"Buffalo3", (uint)SPUpgradeVehicles.Buffalo3 },
            {"Carbonizzare", (uint)OriginalVehicles.Carbonizzare },
            {"Comet2", (uint)OriginalVehicles.Comet2 },
            {"Comet3", (uint)ImportExportVehicles.COMET3 },
            {"Coquette", (uint)OriginalVehicles.Coquette },
            {"Elegy", (uint)ImportExportVehicles.ELEGY },
            {"Elegy2", (uint)OriginalVehicles.Elegy2 },
            {"Feltzer2", (uint)OriginalVehicles.Feltzer2 },
            {"Feltzer3", (uint)IllGottenGainsPt1Vehicles.Feltzer3 },
            {"Furoregt", (uint)LTSVehicles.Furoregt },
            {"Fusilade", (uint)OriginalVehicles.Fusilade },
            {"Futo", (uint)OriginalVehicles.Futo },
            {"Infernus2", (uint)CunningStunts2Vehicles.INFERNUS2 },
            {"Jester", (uint)BusinessVehicles.Jester },
            {"Jester2", (uint)FestiveVehicles.Jester2 },
            {"Khamelion", (uint)OriginalVehicles.Khamelion },
            {"Kuruma", (uint)HeistsVehicles.Kuruma },
            {"Kuruma2", (uint)HeistsVehicles.Kuruma2 },
            {"Lynx", (uint)CunningStuntsVehicles.Lynx },
            {"Massacro", (uint)HighLifeVehicles.Massacro },
            {"Massacro2", (uint)FestiveVehicles.Massacro2 },
            {"Ninef", (uint)OriginalVehicles.Ninef },
            {"Ninef2", (uint)OriginalVehicles.Ninef2 },
            {"Omnis", (uint)CunningStuntsVehicles.Omnis },
            {"Penumbra", (uint)OriginalVehicles.Penumbra },
            {"RapidGT", (uint)OriginalVehicles.RapidGT },
            {"RapidGT2", (uint)OriginalVehicles.RapidGT2 },
            {"Raptor", (uint)Bikers.Raptor },
            {"Ruston", (uint)CunningStunts2Vehicles.RUSTON },
            {"Schafter2", (uint)OriginalVehicles.Schafter2 },
            {"Schafter3", (uint)ExecutiveVehicles.Schafter3 },
            {"Schafter4", (uint)ExecutiveVehicles.Schafter4 },
            {"Schafter5", (uint)ExecutiveVehicles.Schafter5 },
            {"Schafter6", (uint)ExecutiveVehicles.Schafter6 },
            {"Schwarzer", (uint)OriginalVehicles.Schwarzer },
            {"Seven70", (uint)FinanceFelonyVehicles.Seven70 },
            {"Specter", (uint)ImportExportVehicles.SPECTER },
            {"Specter2", (uint)ImportExportVehicles.SPECTER2 },
            {"Sultan", (uint)OriginalVehicles.Sultan },
            {"Surano", (uint)OriginalVehicles.Surano },
            {"Tampa2", (uint)CunningStuntsVehicles.Tampa2 },
            {"Tropos", (uint)CunningStuntsVehicles.Tropos },
            {"Verlierer2", (uint)ExecutiveVehicles.Verlierer2 },
        };
        public static IReadOnlyDictionary<string, uint> SportClassic { get; } = new Dictionary<string, uint>
        {
            {"Ardent", (uint)GunrunningVehicles.ARDENT },
            {"BType", (uint)ValentineVehicles.BType },
            {"BType2", (uint)HalloweenVehicles.BType2 },
            {"BType3", (uint)ValentineVehicles.BType3 },
            {"Casco", (uint)HeistsVehicles.Casco },
            {"Cheetah2", (uint)GunrunningVehicles.CHEETAH2 },
            {"Coquette2", (uint)FlightSchoolVehicles.Coquette2 },
            {"Coquette3", (uint)IllGottenGainsPt2Vehicles.Coquette3 },
            {"JB700", (uint)OriginalVehicles.JB700 },
            {"Mamba", (uint)ExecutiveVehicles.Mamba },
            {"Manana", (uint)OriginalVehicles.Manana },
            {"Monroe", (uint)OriginalVehicles.Monroe },
            {"Peyote", (uint)OriginalVehicles.Peyote },
            {"Pigalle", (uint)HipsterVehicles.Pigalle },
            {"Stinger", (uint)OriginalVehicles.Stinger },
            {"StingerGT", (uint)OriginalVehicles.StingerGT },
            {"Tornado", (uint)OriginalVehicles.Tornado },
            {"Tornado2", (uint)OriginalVehicles.Tornado2 },
            {"Tornado3", (uint)OriginalVehicles.Tornado3 },
            {"Tornado4", (uint)OriginalVehicles.Tornado4 },
            {"Tornado5", (uint)LowriderCCVehicles.Tornado5 },
            {"Tornado6", (uint)Bikers.Tornado6 },
            {"ZType", (uint)OriginalVehicles.ZType },
        };
        public static IReadOnlyDictionary<string, uint> Super { get; } = new Dictionary<string, uint>
        {
            {"Adder", (uint)OriginalVehicles.Adder },
            {"Bullet", (uint)OriginalVehicles.Bullet },
            {"Cheetah", (uint)OriginalVehicles.Cheetah },
            {"EntityXF", (uint)OriginalVehicles.EntityXF },
            {"FMJ", (uint)FinanceFelonyVehicles.FMJ },
            {"GP1", (uint)CunningStunts2Vehicles.GP1 },
            {"Infernus", (uint)OriginalVehicles.Infernus },
            {"LE7B", (uint)CunningStuntsVehicles.LE7B },
            {"Nero", (uint)ImportExportVehicles.NERO },
            {"Nero2", (uint)ImportExportVehicles.NERO2 },
            {"Osiris", (uint)IllGottenGainsPt1Vehicles.Osiris },
            {"Penetrator", (uint)ImportExportVehicles.penetrator },
            {"Pfister811", (uint)FinanceFelonyVehicles.Pfister811 },
            {"Prototipo", (uint)FinanceFelonyVehicles.Prototipo },
            {"Reaper", (uint)FinanceFelonyVehicles.Reaper },
            {"Sheava", (uint)CunningStuntsVehicles.Sheava },
            {"SultanRS", (uint)DropzoneVehicles.SultanRS },
            {"Superd", (uint)OriginalVehicles.Superd },
            {"T20", (uint)IllGottenGainsPt2Vehicles.T20 },
            {"Tempesta", (uint)ImportExportVehicles.TEMPESTA },
            {"Turismo2", (uint)CunningStunts2Vehicles.TURISMO2 },
            {"Turismor", (uint)BusinessVehicles.Turismor },
            {"Tyrus", (uint)CunningStuntsVehicles.Tyrus },
            {"Vacca", (uint)OriginalVehicles.Vacca },
            {"Vagner", (uint)GunrunningVehicles.VAGNER },
            {"Voltic", (uint)OriginalVehicles.Voltic },
            {"Voltic2", (uint)ImportExportVehicles.VOLTIC2 },
            {"Zentorno", (uint)HighLifeVehicles.Zentorno },
            {"Italigtb", (uint)ImportExportVehicles.ITALIGTB },
            {"Italigtb2", (uint)ImportExportVehicles.ITALIGTB2},
            {"XA21", (uint)GunrunningVehicles.XA21 },
        };
        public static IReadOnlyDictionary<string, uint> Trailer { get; } = new Dictionary<string, uint>
        {
            {"ArmyTanker", (uint) OriginalVehicles.ArmyTanker },
            {"ArmyTrailer", (uint) OriginalVehicles.ArmyTrailer },
            {"ArmyTrailer2", (uint) OriginalVehicles.ArmyTrailer2 },
            {"BaleTrailer", (uint) OriginalVehicles.BaleTrailer },
            {"BoatTrailer", (uint) OriginalVehicles.BoatTrailer },
            {"CableCar", (uint) OriginalVehicles.CableCar },
            {"DockTrailer", (uint) OriginalVehicles.DockTrailer },
            {"GrainTrailer", (uint) OriginalVehicles.GrainTrailer },
            {"PropTrailer", (uint) OriginalVehicles.PropTrailer },
            {"RakeTrailer", (uint) OriginalVehicles.RakeTrailer },
            {"TR2", (uint) OriginalVehicles.TR2 },
            {"TR3", (uint) OriginalVehicles.TR3 },
            {"TR4", (uint) OriginalVehicles.TR4 },
            {"TRFlat", (uint) OriginalVehicles.TRFlat },
            {"TVTrailer", (uint) OriginalVehicles.TVTrailer },
            {"Tanker", (uint) OriginalVehicles.Tanker },
            {"Tanker2", (uint) HeistsVehicles.Tanker2 },
            {"TrailerLogs", (uint) OriginalVehicles.TrailerLogs },
            {"TrailerSmall", (uint) OriginalVehicles.TrailerSmall },
            {"Trailers", (uint) OriginalVehicles.Trailers },
            {"Trailers2", (uint) OriginalVehicles.Trailers2 },
            {"Trailers3", (uint) OriginalVehicles.Trailers3 },
        };
        public static IReadOnlyDictionary<string, uint> Train { get; } = new Dictionary<string, uint>
        {
            {"Freight", (uint) OriginalVehicles.Freight },
            {"FreightCar", (uint) OriginalVehicles.FreightCar },
            {"FreightCont1", (uint) OriginalVehicles.FreightCont1 },
            {"FreightCont2", (uint) OriginalVehicles.FreightCont2 },
            {"FreightGrain", (uint) OriginalVehicles.FreightGrain },
            {"FreightTrailer", (uint)OriginalVehicles.FreightTrailer },
            {"TankerCar", (uint) OriginalVehicles.TankerCar },
        };
        public static IReadOnlyDictionary<string, uint> Utility { get; } = new Dictionary<string, uint>
        {
            {"Airtug", (uint) OriginalVehicles.Airtug },
            {"Caddy", (uint) OriginalVehicles.Caddy },
            {"Caddy2", (uint) OriginalVehicles.Caddy2 },
            {"Caddy3", (uint) GunrunningVehicles.CADDY3 },
            {"Docktug", (uint) OriginalVehicles.Docktug },
            {"Forklift", (uint)OriginalVehicles.Forklift },
            {"Mower", (uint) OriginalVehicles.Mower },
            {"Ripley", (uint) OriginalVehicles.Ripley },
            {"Sadler", (uint)OriginalVehicles.Sadler },
            {"Scrap", (uint) OriginalVehicles.Scrap },
            {"TowTruck", (uint) OriginalVehicles.TowTruck },
            {"TowTruck2", (uint)OriginalVehicles.TowTruck2 },
            {"Tractor", (uint) OriginalVehicles.Tractor },
            {"Tractor2", (uint) OriginalVehicles.Tractor2 },
            {"Tractor3", (uint)OriginalVehicles.Tractor3 },
            {"Trailer", (uint) GunrunningVehicles.TRAILER },
            {"TrailerLarge", (uint) GunrunningVehicles.TRLARGE },
            {"TrailerS4", (uint) GunrunningVehicles.TRSMALL2 },
            {"UtilliTruck", (uint) OriginalVehicles.UtilliTruck },
            {"UtilliTruck3", (uint) OriginalVehicles.UtilliTruck3 },
            {"UtilliTruck2", (uint) OriginalVehicles.UtilliTruck2 },
        };
        public static IReadOnlyDictionary<string, uint> Van { get; } = new Dictionary<string, uint>
        {
            {"Bison", (uint) OriginalVehicles.Bison },
            {"Bison2", (uint) OriginalVehicles.Bison2 },
            {"Bison3", (uint) OriginalVehicles.Bison3 },
            {"BobcatXL", (uint) OriginalVehicles.BobcatXL },
            {"Boxville", (uint) OriginalVehicles.Boxville },
            {"Boxville2", (uint)OriginalVehicles.Boxville2 },
            {"Boxville3", (uint) OriginalVehicles.Boxville3 },
            {"Boxville4", (uint) HeistsVehicles.Boxville4 },
            {"Boxville5", (uint) ImportExportVehicles.BOXVILLE5 },
            {"Burrito", (uint) OriginalVehicles.Burrito },
            {"Burrito2", (uint) OriginalVehicles.Burrito2 },
            {"Burrito3", (uint) OriginalVehicles.Burrito3 },
            {"Burrito4", (uint)OriginalVehicles.Burrito4 },
            {"Burrito5", (uint)OriginalVehicles.Burrito5 },
            {"Camper", (uint) OriginalVehicles.Camper },
            {"GBurrito", (uint) OriginalVehicles.GBurrito },
            {"GBurrito2", (uint) HeistsVehicles.GBurrito2 },
            {"Journey", (uint)OriginalVehicles.Journey },
            {"Minivan", (uint)OriginalVehicles.Minivan },
            {"Minivan2", (uint) LowriderCCVehicles.Minivan2 },
            {"Paradise", (uint) BeachBumVehicles.Paradise },
            {"Pony", (uint) OriginalVehicles.Pony },
            {"Pony2", (uint)OriginalVehicles.Pony2 },
            {"Rumpo", (uint)OriginalVehicles.Rumpo },
            {"Rumpo2", (uint)OriginalVehicles.Rumpo2 },
            {"Rumpo3", (uint) FinanceFelonyVehicles.Rumpo3 },
            {"Speedo", (uint) OriginalVehicles.Speedo },
            {"Speedo2", (uint) OriginalVehicles.Speedo2 },
            {"Surfer", (uint)OriginalVehicles.Surfer },
            {"Surfer2", (uint)OriginalVehicles.Surfer2 },
            {"Taco", (uint)OriginalVehicles.Taco },
            {"Youga", (uint)OriginalVehicles.Youga },
            {"Youga2", (uint)Bikers.Youga2 },
        };
    }
}
