using System.Collections.Generic;

namespace GTAN.Data
{
    public static class Extras
    {
        public static IReadOnlyList<string> WebsiteDicts = new List<string>
        {
            "candc_apartments",
            "candc_default",
            "candc_executive1",
            "candc_gunrunning",
            "candc_importexport",
            "candc_truck",
            "dock_default",
            "dock_dlc_executive1",
            "elt_default",
            "elt_dlc_apartments",
            "elt_dlc_business",
            "elt_dlc_executive1",
            "elt_dlc_luxe",
            "elt_dlc_pilot",
            "foreclosures_bunker",
            "lgm_default",
            "lgm_dlc_apartments",
            "lgm_dlc_biker",
            "lgm_dlc_business2",
            "lgm_dlc_business",
            "lgm_dlc_executive1",
            "lgm_dlc_gunrunning",
            "lgm_dlc_heist",
            "lgm_dlc_importexport",
            "lgm_dlc_lts_creator",
            "lgm_dlc_luxe",
            "lgm_dlc_pilot",
            "lgm_dlc_specialraces",
            "lgm_dlc_stunt",
            "lgm_dlc_valentines2",
            "lgm_dlc_valentines",
            "lsc_default",
            "lsc_dlc_import_export",
            "lsc_lowrider2",
            "lsc_jan2016",
            "pandm_default",
            "sssa_default",
            "sssa_dlc_biker",
            "sssa_dlc_business",
            "sssa_dlc_business2",
            "sssa_dlc_christmas_2",
            "sssa_dlc_christmas_3",
            "sssa_dlc_executive_1",
            "sssa_dlc_halloween",
            "sssa_dlc_heist",
            "sssa_dlc_hipster",
            "sssa_dlc_independence",
            "sssa_dlc_lts_creator",
            "sssa_dlc_mp_to_sp",
            "sssa_dlc_stunt",
            "sssa_dlc_valentines",
            "candc_smuggler",
            "elt_dlc_smuggler",
            "lgm_dlc_smuggler",
            "sssa_dlc_smuggler",
            "candc_xmas2017",
            "lgm_dlc_xmas2017",
            "sssa_dlc_xmas2017",
        };
        //public Dictionary<string, object> DLCS = new Dictionary<string, Enum>
        //{
        //    {"Original game", OriginalVehicles},
        //    {"Returning Player", SPUpgradeVehicles} ,
        //    {"Beach Bum", BeachBumVehicles},
        //    {"Valentines Day Massacre", ValentineVehicles},
        //    {"The Business Update", BusinessVehicles},
        //    {"The High Life", HighLifeVehicles},
        //    {"I'm Not A Hipster", HipsterVehicles},
        //    {"Independence Day", MURKAVehicles},
        //    {"SA Flight School", FlightSchoolVehicles},
        //    {"Last Team Standing", LTSVehicles},
        //    {"Festive Surprise", FestiveVehicles},
        //    {"Heists", HeistsVehicles},
        //    {"Ill-Gotten Gains Pt1", IllGottenGainsPt1Vehicles},
        //    {"Ill-Gotten Gains Pt2", IllGottenGainsPt2Vehicles},
        //    {"Lowriders", LowriderVehicles},
        //    {"Halloween Surprise", HalloweenVehicles},
        //    {"Executives and Other Criminals", ExecutiveVehicles},
        //    {"Drop Zone", DropzoneVehicles},
        //    {"Lowriders: Custom Classics", LowriderCCVehicles},
        //    {"Further Adventures in Finance and Felony", FinanceFelonyVehicles},
        //    {"Cunning Stunts", CunningStuntsVehicles},
        //    {"Bikers", BikersVehicles},
        //    {"Import/Export", ImportExportVehicles},
        //    {"Cunning Stunts: Special Vehicle Circuit", CunningStunts2Vehicles},
        //    {"Gunrunning", GunrunningVehicles},
        //    {"Smuggler's Run", SmugglersRunVehicles},
        //    {"Doomsday Heist", DoomsdayHeistVehicles},
        //    {"Southern San Andreas Super Sport Series", SSASSSVehicles},
        //    {"After Hours", AfterHoursVehicles},
        //    {"Arena War", ArenaWarVehicles},
        //};  
    }
}