namespace GTAN.Data.Decision
{
    public enum Shocking
    {
        CEventShockingCarAlarm = 75,
        CEventShockingCarChase = 76,
        CEventShockingCarCrash = 77,
        CEventShockingBicycleCrash = 78,
        CEventShockingCarPileUp = 79,
        CEventShockingCarOnCar = 80,
        CEventShockingDangerousAnimal = 81,
        CEventShockingDeadBody = 82,
        CEventShockingDrivingOnPavement = 83,
        CEventShockingEngineRevved = 85,
        CEventShockingExplosion = 86,
        CEventShockingFire = 87,
        CEventShockingGunFight = 88,
        CEventShockingGunshotFired = 89,
        CEventShockingHelicopterOverhead = 90,
        CEventShockingParachuterOverhead = 91,
        CEventShockingHornSounded = 93,
        CEventShockingInjuredPed = 95,
        CEventShockingMadDriver = 96,
        CEventShockingMadDriverExtreme = 97,
        CEventShockingMugging = 99,
        CEventShockingNonViolentWeaponAimedAt = 100,
        CEventShockingPedRunOver = 101,
        CEventShockingPedShot = 102,
        CEventShockingPlaneFlyby = 103,
        CEventShockingPropertyDamage = 104,
        CEventShockingPropertyDamage2 = 105,
        CEventShockingRunningPed = 106,
        CEventShockingRunningStampede = 107,
        CEventShockingSeenCarStolen = 108,
        CEventShockingSeenConfrontation = 109,
        CEventShockingSeenGangFight = 110,
        CEventShockingSeenInsult = 111,
        CEventShockingSeenMeleeAction = 112,
        CEventShockingSeenNiceCar = 113,
        CEventShockingSeenPedKilled = 114,
        CEventShockingVehicleTowed = 115,
        CEventShockingWeaponThreat = 116,
        CEventShockingWeirdPed = 117,
        CEventShockingWeirdPedApproaching = 118,
        CEventShockingSiren = 119,
        CEventShockingStudioBomb = 120,
        CEventShockingVisibleWeapon = 121,
    }
}
